### ISSUE TITLE
Query applied to gist geojson file

### ISSUE THREAD

**Issue by aborruso** [koopjs/koop#291] opened 2016-07-26 10:26 UTC
Hi,
is it possible with koop to run a query on a gist geojson object?

Something like http://koop..../gist/6178185/query?where=ZIP=60647 ?

Thank you

**Comment by dmfenton** [comment] 2016-08-22 12:22
The query method will only work against feature server endpoints. However, you should be able to drop `/query` and send the same url to get a filtered set of features.

Also take a look at using Winnow for querying against arbitrary geojson objects. https://github.com/dmfenton/winnow

**Comment by aborruso** [comment] 2016-08-22 16:38
On 22 August 2016 at 14:22, Daniel Fenton <notifications@github.com> wrote:

> The query method will only work against feature server endpoints. However,
> you should be able to drop /query and send the same url to get a filtered
> set of features.
>
I have just tested this URL http://koop.dc.esri.com/gist/6178185?where=id=28
and I do not have the filtered set of features.

Thank you for winnow!

**Comment by jgravois** [comment] 2016-08-22 16:42
> I have just tested this URL http://koop.dc.esri.com/gist/6178185?where=id=28
and I do not have the filtered set of features.

the same inappropriate behavior is repoducible from the **/FeatureServer/** endpoint too.

http://koop.dc.esri.com/gist/6178185/FeatureServer/0/query/?where=id=28

**Comment by aborruso** [comment] 2016-08-22 16:46
@jgravois if you read [this reply](https://github.com/koopjs/koop/issues/291#issuecomment-241396395) of @dmfenton , he says in reply to [this](https://github.com/koopjs/koop/issues/291#issue-167573894) message of mine:

> However, you should be able to drop /query and send the same url to get a filtered set of features.

Than I have made this test

**Comment by jgravois** [comment] 2016-08-22 16:54
i guess i don't follow you.

1. you asked whether it was possible to filter geojson from a gist
2. @dmfenton said the feature server endpoints support a query method and suggested a technique for you to use to filter raw gist geojson as well.
3. you reported that the technique he suggested doesn't return what you expected
4. i reported that the feature server query method also seems incapable of filtering

**Comment by dmfenton** [comment] 2016-08-22 17:05
> I have just tested this URL http://koop.dc.esri.com/gist/6178185?where=id=28
and I do not have the filtered set of features.

Unfortunately, the queries will only work if the id's are part of the `properties` in the original data. The id's you see in the response are added after the fact for compatibility with ArcGIS.

**Comment by aborruso** [comment] 2016-08-22 17:07
@jgravois I'm sorry, my fault.

You are right. And it does not work also in this way:

http://koop.dc.esri.com/gist/6178185/FeatureServer/0/query?idField=1

It should work (I have read it here http://tldrify.com/jf9)

**Comment by dmfenton** [comment] 2016-08-22 17:08
I as mentioned above, the query you are trying will only work if the source data has an id field.

**Comment by aborruso** [comment] 2016-08-22 17:15
On 22 August 2016 at 19:05, Daniel Fenton <notifications@github.com> wrote:

> Unfortunately, the queries will only work if the id's are part of the
> properties in the original data.
>
I have tried with this
http://koop.dc.esri.com/gist/6174da716448b9d25ed2ed7cbd436da2?where=stop_code=345
(stop_code
is a property) and I have no result.

Thank you again

___________________

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by dmfenton** [comment] 2016-08-22 17:17
Ok, I'm not sure what is going on here as I did not write this provider. I'll have to dig deeper to debug when I have time.

**Comment by dmfenton** [comment] 2017-02-22 15:51
This is a dupe of #227

**Closed by dmfenton** 2017-02-22 15:51 UTC
